version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/catalystgo/main.go
    id: "catalystgo"
    binary: catalystgo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - main: ./cmd/protoc-gen-catalystgo/main.go
    id: "protoc-gen-catalystgo"
    binary: protoc-gen-catalystgo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
