version: '3'

vars:
  # GENERAL
  GOBIN: "$(pwd)/bin"

  # DB
  DB_DSN: "user=postgres dbname={{.AppName}} password=postgres sslmode=disable"
  MIGRATION_DIR: "./migrations"

tasks:
  run:
    cmds:
      - |
        export GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn
        go run ./cmd/.

  mock:
    cmds:
      - echo "mocking!"
      # - mockgen -source=./internal/mock/mock.go -destination=./internal/mock/mock.go -package=mock

  generate:
    cmds:
      # Generate
      - "{{.GOBIN}}/buf generate --template buf.gen.vendor.yaml"
      - "{{.GOBIN}}/buf generate --template buf.gen.yaml"
      - go mod tidy
    deps:
      - deps
      - vendor

  format:
    cmds:
      - task: go_files
        vars: { COMMAND: "gofmt -w  {} +"}
      - task: go_files
        vars: { COMMAND: "{{.GOBIN}}/goimports -w  {} +"}

  test:
    cmds:
      - go test -v -race -cover ./...

  lint:
    cmds:
      - "{{.GOBIN}}/revive
        -config revive.toml
        -formatter friendly
        -exclude ./mock
        -exclude ./internal/pb
        ./..."

  deps:
    cmds:
      # GRPC
      - GOBIN={{.GOBIN}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.16.0
      - GOBIN={{.GOBIN}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.16.0
      - GOBIN={{.GOBIN}} go install github.com/planetscale/vtprotobuf/cmd/protoc-gen-go-vtproto@v0.6.0
      - GOBIN={{.GOBIN}} go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1
      - GOBIN={{.GOBIN}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0
      - GOBIN={{.GOBIN}} go install github.com/bufbuild/buf/cmd/buf@v1.31.0
      - GOBIN={{.GOBIN}} go install github.com/catalystgo/cli/cmd/catalystgo@v0.0.3

      # TOOLS
      - GOBIN={{.GOBIN}} go install github.com/pressly/goose/v3/cmd/goose@v3.20.0
      - GOBIN={{.GOBIN}} go install golang.org/x/tools/cmd/goimports@v0.19.0
      - GOBIN={{.GOBIN}} go install github.com/mgechev/revive@v1.3.7
      - GOBIN={{.GOBIN}} go install github.com/google/yamlfmt/cmd/yamlfmt@v0.12.1
      - pip install pre-commit

## DOCKER

  docker-up:
    cmds:
      - docker compose up -f .deployment/docker-compose.yml

  docker-down:
    cmds:
      - docker compose down -f .deployment/docker-compose.yml

# MIGRATIONS

  goose-add:
    cmds:
    - "{{.GOBIN}}/goose -dir {{.MIGRATION_DIR}} create fix_me sql"

  goose-status:
    cmds:
      - "{{.GOBIN}}/goose -dir {{.MIGRATION_DIR}} postgres \"{{.DB_DSN}}\" status"

  goose-up:
    cmds:
    - "{{.GOBIN}}/goose -dir {{.MIGRATION_DIR}} postgres \"{{.DB_DSN}}\" up"

  goose-down:
    cmds:
      - "{{.GOBIN}}/goose -dir {{.MIGRATION_DIR}} postgres \"{{.DB_DSN}}\" down"

## INTERNAL COMMANDS

  go_files:
    desc: "Return all .go files and run .COMMAND on them"
    internal: true
    cmds:
     - find .
        -name "*.go"
        -not -path ./mock
        -exec {{.COMMAND}};
